# Generated by Django 5.2.8 on 2025-11-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(choices=[('oftalmologia', 'Oftalmologia'), ('cardiologia', 'Cardiologia'), ('dermatologia', 'Dermatologia')], default='Clínico Geral', max_length=255)),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('cpf', models.CharField(default='00000000000', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(default=0)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('contato', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(db_index=True)),
                ('situacao', models.CharField(choices=[('AG', 'Agendada'), ('RE', 'Realizada'), ('CA', 'Cancelada')], default='AG', max_length=2)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='hospital.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='hospital.paciente')),
            ],
        ),
    ]
