# Generated by Django 5.2.8 on 2025-11-19 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='hospital.medico'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='hospital.paciente'),
        ),
    ]
