# Generated by Django 5.2.7 on 2025-11-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_medico_cpf_paciente_cpf_alter_consulta_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
