# Generated by Django 5.2.8 on 2025-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_paciente_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='idade',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(choices=[('oftalmologia', 'Oftalmologia'), ('cardiologia', 'Cardiologia'), ('dermatologia', 'Dermatologia')], default='Clínico Geral', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contato',
            field=models.CharField(max_length=15),
        ),
    ]
